services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3307:3306'
    environment:
      - 'MYSQL_DATABASE=game_truth'
      - 'MYSQL_PASSWORD=Soadsoil1412!'
      - 'MYSQL_ROOT_PASSWORD=Soadsoil1412!'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
